package com.bw.kongchenliang.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bw.kongchenliang.bean.FoodEntitiy;

import com.bw.kongchenliang.db.FoodEntitiyDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig foodEntitiyDaoConfig;

    private final FoodEntitiyDao foodEntitiyDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        foodEntitiyDaoConfig = daoConfigMap.get(FoodEntitiyDao.class).clone();
        foodEntitiyDaoConfig.initIdentityScope(type);

        foodEntitiyDao = new FoodEntitiyDao(foodEntitiyDaoConfig, this);

        registerDao(FoodEntitiy.class, foodEntitiyDao);
    }
    
    public void clear() {
        foodEntitiyDaoConfig.clearIdentityScope();
    }

    public FoodEntitiyDao getFoodEntitiyDao() {
        return foodEntitiyDao;
    }

}
