package com.bw.kongchenliang.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bw.kongchenliang.bean.FoodEntitiy;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FOOD_ENTITIY".
*/
public class FoodEntitiyDao extends AbstractDao<FoodEntitiy, Long> {

    public static final String TABLENAME = "FOOD_ENTITIY";

    /**
     * Properties of entity FoodEntitiy.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Price = new Property(2, int.class, "price", false, "PRICE");
        public final static Property Img = new Property(3, String.class, "img", false, "IMG");
        public final static Property Ischeck = new Property(4, boolean.class, "ischeck", false, "ISCHECK");
    }


    public FoodEntitiyDao(DaoConfig config) {
        super(config);
    }
    
    public FoodEntitiyDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FOOD_ENTITIY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TITLE\" TEXT," + // 1: title
                "\"PRICE\" INTEGER NOT NULL ," + // 2: price
                "\"IMG\" TEXT," + // 3: img
                "\"ISCHECK\" INTEGER NOT NULL );"); // 4: ischeck
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FOOD_ENTITIY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, FoodEntitiy entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
        stmt.bindLong(3, entity.getPrice());
 
        String img = entity.getImg();
        if (img != null) {
            stmt.bindString(4, img);
        }
        stmt.bindLong(5, entity.getIscheck() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, FoodEntitiy entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
        stmt.bindLong(3, entity.getPrice());
 
        String img = entity.getImg();
        if (img != null) {
            stmt.bindString(4, img);
        }
        stmt.bindLong(5, entity.getIscheck() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public FoodEntitiy readEntity(Cursor cursor, int offset) {
        FoodEntitiy entity = new FoodEntitiy( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // title
            cursor.getInt(offset + 2), // price
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // img
            cursor.getShort(offset + 4) != 0 // ischeck
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, FoodEntitiy entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTitle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPrice(cursor.getInt(offset + 2));
        entity.setImg(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setIscheck(cursor.getShort(offset + 4) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(FoodEntitiy entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(FoodEntitiy entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(FoodEntitiy entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
